### ISSUE TITLE
Database error 1055

### ISSUE THREAD

**Issue by jsrothwell** [MitchellMcKenna/LifePress#58]
Hi there,

Not sure if anyone is still around but I am getting a mysql error of 1055 when i try to load this up

Error Number: 1055

Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'xxxxxxx.feeds.feed_icon' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SELECT `feed_domain`, `feed_icon` FROM (`feeds`) WHERE `feed_status` = 'active' GROUP BY `feed_domain`

**Comment by baileylo** [comment]
@jsrothwell I've created a PR and linked this ticket. I don't have MySQL 5.7 installed, so I did my best trying to figure if there were other cases and I think this is it. If you want to give it a go and let me know if there are other errors I'd be much appreciative.

**Comment by jsrothwell** [comment]
Willdo. Ive been trying to get it up and running and will make a fork and submit any errors I have and can fix.

**Comment by baileylo** [comment]
Thanks! I got it running in php 7 yesterday I can merge that code as well
if that will help you

**Comment by MitchellMcKenna** [comment]
Well would you look at that, LifePress works on PHP 7 with mysql 5.7 (besides this error of course), if you turn off all the deprecation warnings, lol.

@baileylo Thanks for the fix!

**Comment by MitchellMcKenna** [comment]
For anyone who stumbles on this from google search results, here is the official mysql page of the cause of and possible fixes for the problem: https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html
